- hosts: all
  become: true
  become_user: root
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /home/akram/tp3-devops-k8s/Deployment.yml --kubeconfig=/home/akram/.kube/config
      ignore_errors: true
    - name: delete old service
      command: kubectl delete -f /home/akram/tp3-devops-k8s/Service.yml --kubeconfig=/home/akram/.kube/config
      ignore_errors: true
    - name: create new deployment
      command: kubectl apply -f //home/akram/tp3-devops-k8s/Deployment.yml --kubeconfig=/home/akram/.kube/config
    - name: create new service
      command: kubectl apply -f /home/akram/tp3-devops-k8s/Service.yml --force --kubeconfig=/home/akram/.kube/config
